// tinyfetch Copyright (C) 2024 kernaltrap8
// This program comes with ABSOLUTELY NO WARRANTY
// This is free software, and you are welcome to redistribute it
// under certain conditions

/*
    tinyascii.h
*/

// ASCII art for distros
// art generated using figlet: http://www.figlet.org/

// Auto-generated by gen_ascii.sh
// Do not edit manually

char *a_p1 = "            ";
char *a_p2 = "  __ _      ";
char *a_p3 = " / _` |     ";
char *a_p4 = "| (_| |     ";
char *a_p5 = " \\__,_|    ";
char *a_p6 = "            ";
char *a_p7 = "            ";
char *a_p8 = "            ";
char *a_p9 = "            ";

char *b_p1 = " _          ";
char *b_p2 = "| |__       ";
char *b_p3 = "| '_ \\     ";
char *b_p4 = "| |_) |     ";
char *b_p5 = "|_.__/      ";
char *b_p6 = "            ";
char *b_p7 = "            ";
char *b_p8 = "            ";
char *b_p9 = "            ";

char *c_p1 = "            ";
char *c_p2 = "  ___       ";
char *c_p3 = " / __|      ";
char *c_p4 = "| (__       ";
char *c_p5 = " \\___|     ";
char *c_p6 = "            ";
char *c_p7 = "            ";
char *c_p8 = "            ";
char *c_p9 = "            ";

char *d_p1 = "     _      ";
char *d_p2 = "  __| |     ";
char *d_p3 = " / _` |     ";
char *d_p4 = "| (_| |     ";
char *d_p5 = " \\__,_|    ";
char *d_p6 = "            ";
char *d_p7 = "            ";
char *d_p8 = "            ";
char *d_p9 = "            ";

char *e_p1 = "            ";
char *e_p2 = "  ___       ";
char *e_p3 = " / _ \\     ";
char *e_p4 = "|  __/      ";
char *e_p5 = " \\___|     ";
char *e_p6 = "            ";
char *e_p7 = "            ";
char *e_p8 = "            ";
char *e_p9 = "            ";

char *f_p1 = "  __        ";
char *f_p2 = " / _|       ";
char *f_p3 = "| |_        ";
char *f_p4 = "|  _|       ";
char *f_p5 = "|_|         ";
char *f_p6 = "            ";
char *f_p7 = "            ";
char *f_p8 = "            ";
char *f_p9 = "            ";

char *g_p1 = "            ";
char *g_p2 = "  __ _      ";
char *g_p3 = " / _` |     ";
char *g_p4 = "| (_| |     ";
char *g_p5 = " \\__, |    ";
char *g_p6 = " |___/      ";
char *g_p7 = "            ";
char *g_p8 = "            ";
char *g_p9 = "            ";

char *h_p1 = " _          ";
char *h_p2 = "| |__       ";
char *h_p3 = "| '_ \\     ";
char *h_p4 = "| | | |     ";
char *h_p5 = "|_| |_|     ";
char *h_p6 = "            ";
char *h_p7 = "            ";
char *h_p8 = "            ";
char *h_p9 = "            ";

char *i_p1 = " _          ";
char *i_p2 = "(_)         ";
char *i_p3 = "| |         ";
char *i_p4 = "| |         ";
char *i_p5 = "|_|         ";
char *i_p6 = "            ";
char *i_p7 = "            ";
char *i_p8 = "            ";
char *i_p9 = "            ";

char *j_p1 = "   _        ";
char *j_p2 = "  (_)       ";
char *j_p3 = "  | |       ";
char *j_p4 = "  | |       ";
char *j_p5 = " _/ |       ";
char *j_p6 = "|__/        ";
char *j_p7 = "            ";
char *j_p8 = "            ";
char *j_p9 = "            ";

char *k_p1 = " _          ";
char *k_p2 = "| | __      ";
char *k_p3 = "| |/ /      ";
char *k_p4 = "|   <       ";
char *k_p5 = "|_|\\_\\    ";
char *k_p6 = "            ";
char *k_p7 = "            ";
char *k_p8 = "            ";
char *k_p9 = "            ";

char *l_p1 = " _          ";
char *l_p2 = "| |         ";
char *l_p3 = "| |         ";
char *l_p4 = "| |         ";
char *l_p5 = "|_|         ";
char *l_p6 = "            ";
char *l_p7 = "            ";
char *l_p8 = "            ";
char *l_p9 = "            ";

char *m_p1 = "            ";
char *m_p2 = " _ __ ___   ";
char *m_p3 = "| '_ ` _ \\ ";
char *m_p4 = "| | | | | | ";
char *m_p5 = "|_| |_| |_| ";
char *m_p6 = "            ";
char *m_p7 = "            ";
char *m_p8 = "            ";
char *m_p9 = "            ";

char *n_p1 = "            ";
char *n_p2 = " _ __       ";
char *n_p3 = "| '_ \\     ";
char *n_p4 = "| | | |     ";
char *n_p5 = "|_| |_|     ";
char *n_p6 = "            ";
char *n_p7 = "            ";
char *n_p8 = "            ";
char *n_p9 = "            ";

char *o_p1 = "            ";
char *o_p2 = "  ___       ";
char *o_p3 = " / _ \\     ";
char *o_p4 = "| (_) |     ";
char *o_p5 = " \\___/     ";
char *o_p6 = "            ";
char *o_p7 = "            ";
char *o_p8 = "            ";
char *o_p9 = "            ";

char *p_p1 = "            ";
char *p_p2 = " _ __       ";
char *p_p3 = "| '_ \\     ";
char *p_p4 = "| |_) |     ";
char *p_p5 = "| .__/      ";
char *p_p6 = "|_|         ";
char *p_p7 = "            ";
char *p_p8 = "            ";
char *p_p9 = "            ";

char *q_p1 = "            ";
char *q_p2 = "  __ _      ";
char *q_p3 = " / _` |     ";
char *q_p4 = "| (_| |     ";
char *q_p5 = " \\__, |    ";
char *q_p6 = "    |_|     ";
char *q_p7 = "            ";
char *q_p8 = "            ";
char *q_p9 = "            ";

char *r_p1 = "            ";
char *r_p2 = " _ __       ";
char *r_p3 = "| '__|      ";
char *r_p4 = "| |         ";
char *r_p5 = "|_|         ";
char *r_p6 = "            ";
char *r_p7 = "            ";
char *r_p8 = "            ";
char *r_p9 = "            ";

char *s_p1 = "            ";
char *s_p2 = " ___        ";
char *s_p3 = "/ __|       ";
char *s_p4 = "\\__ \\     ";
char *s_p5 = "|___/       ";
char *s_p6 = "            ";
char *s_p7 = "            ";
char *s_p8 = "            ";
char *s_p9 = "            ";

char *t_p1 = " _          ";
char *t_p2 = "| |_        ";
char *t_p3 = "| __|       ";
char *t_p4 = "| |_        ";
char *t_p5 = " \\__|      ";
char *t_p6 = "            ";
char *t_p7 = "            ";
char *t_p8 = "            ";
char *t_p9 = "            ";

char *u_p1 = "            ";
char *u_p2 = " _   _      ";
char *u_p3 = "| | | |     ";
char *u_p4 = "| |_| |     ";
char *u_p5 = " \\__,_|    ";
char *u_p6 = "            ";
char *u_p7 = "            ";
char *u_p8 = "            ";
char *u_p9 = "            ";

char *v_p1 = "            ";
char *v_p2 = "__   __     ";
char *v_p3 = "\\ \\ / /   ";
char *v_p4 = " \\ V /     ";
char *v_p5 = "  \\_/      ";
char *v_p6 = "            ";
char *v_p7 = "            ";
char *v_p8 = "            ";
char *v_p9 = "            ";

char *w_p1 = "            ";
char *w_p2 = "__      __  ";
char *w_p3 = "\\ \\ /\\ / ";
char *w_p4 = " \\ V  V /  ";
char *w_p5 = "  \\_/\\_/  ";
char *w_p6 = "            ";
char *w_p7 = "            ";
char *w_p8 = "            ";
char *w_p9 = "            ";

char *x_p1 = "            ";
char *x_p2 = "__  __      ";
char *x_p3 = "\\ \\/ /    ";
char *x_p4 = " >  <       ";
char *x_p5 = "/_/\\_\\    ";
char *x_p6 = "            ";
char *x_p7 = "            ";
char *x_p8 = "            ";
char *x_p9 = "            ";

char *y_p1 = "            ";
char *y_p2 = " _   _      ";
char *y_p3 = "| | | |     ";
char *y_p4 = "| |_| |     ";
char *y_p5 = " \\__, |    ";
char *y_p6 = " |___/      ";
char *y_p7 = "            ";
char *y_p8 = "            ";
char *y_p9 = "            ";

char *z_p1 = "            ";
char *z_p2 = " ____       ";
char *z_p3 = "|_  /       ";
char *z_p4 = " / /        ";
char *z_p5 = "/___|       ";
char *z_p6 = "            ";
char *z_p7 = "            ";
char *z_p8 = "            ";
char *z_p9 = "            ";

